4th semester university/Lab4/mysite/auth_user/urls.py
import auth_user.views
from django.urls import path

from .models import RegisterUser, LoginUser

app_name = 'auth_user'

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', auth_user.views.logout_user, name='logout')
]

4th semester university/Lab4/mysite/faq/urls.py
from . import views
from django.urls import path

app_name = 'faq'

urlpatterns = [
    path('', views.faq_list, name='home'),
]

4th semester university/Lab4/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('hotel/', include('hotel.urls', namespace='hotel')),
    path('auth/', include('auth_user.urls', namespace='auth_user')),
    path('profile/', include('profile_user.urls', namespace='profile_user')),
    path('news/', include('news.urls', namespace='news')),
    path('about/', include('about.urls', namespace='about')),
    path('faq/', include('faq.urls', namespace='faq')),
    path('employee/', include('employee.urls', namespace='employee')),
    path('vacancy/', include('vacancy.urls', namespace='vacancy')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('review/', include('review.urls', namespace='review')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4th semester university/Lab4/mysite/profile_user/urls.py
from . import views
from django.urls import path

app_name = 'profile_user'

urlpatterns = [
    path('', views.get_book, name='profile'),
]

4th semester university/Lab4/mysite/review/urls.py
from . import views
from django.urls import path

app_name = 'review'

urlpatterns = [
    path('', views.review_list, name='home'),
]

4th semester university/Lab4/mysite/review/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from hotel.models import Client


class Review(models.Model):
    author = models.ForeignKey(Client, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Отзыв от {self.author} оценка: {self.rating}"

4th semester university/Lab4/mysite/review/views.py
from django.shortcuts import render
from .models import Review


def review_list(request):
    reviews = Review.objects.all()
    context = {'reviews': reviews}
    return render(request, 'review.html', context)

4th semester university/Lab4/mysite/review/templates/review.html
{% extends 'hotel/base_hotel.html' %}

{% block head %}
<meta name="description" content="Отзывы о нашей компании">
<meta name="keywords" content="отзывы, обратная связь, рейтинг, оценки">
<link rel="stylesheet" href="/static/css/review.css">
{% endblock %}

{% block content %}


<div class="loader2"></div>
<div class="date">
    <label for="birthdate" id="text">Введите вашу дату рождения:</label>
    <input class="input-1 " type="date" id="birthdate">
    <button class="button-1 " id="calculateAge">Check</button>
</div>
<script src="/static/js/check_date.js"></script>

<h1>Отзывы</h1>

{% if user.is_authenticated %}
<label class="review" onclick="window.location.href='{%url 'profile_user:profile' %}';">Добавить отзыв</label>
{% else %}
<label class="review" onclick="window.location.href='{%url 'auth_user:register' %}';">Добавить отзыв</label>
{% endif %}

<ul>
    {% for review in reviews %}
    <li itemscope itemtype="http://schema.org/Review">
        <p itemprop="author">Автор: {{ review.author }}</p>
        <p itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
            Оценка: <span itemprop="ratingValue">{{ review.rating }}</span>
        </p>
        <p itemprop="reviewBody">{{ review.text }}</p>
        <p itemprop="datePublished">Дата: {{ review.date }}</p>
    </li>
    {% endfor %}
</ul>

{% endblock %}