4th semester university/Lab4/mysite/auth_user/urls.py
import auth_user.views
from django.urls import path

from .models import RegisterUser, LoginUser

app_name = 'auth_user'

urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', auth_user.views.logout_user, name='logout')
]

4th semester university/Lab4/mysite/faq/urls.py
from . import views
from django.urls import path

app_name = 'faq'

urlpatterns = [
    path('', views.faq_list, name='home'),
]

4th semester university/Lab4/mysite/hotel/urls.py
from . import views
from django.urls import path

app_name = 'hotel'

urlpatterns = [
    path('sort_by/<int:category_id>/', views.room_list, name='hotel_list'),
    path('sort_by/<int:category_id>/sort_by_price/', views.sort_rooms_by_price, name='hotel_list_sort_by_price'),
    path('room/<int:room_id>', views.room_detail, name='room_id'),
    path('add/', views.create_room, name='room_create'),
    path('analyse/', views.analyse, name='hotel_analyse')
]

4th semester university/Lab4/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('hotel/', include('hotel.urls', namespace='hotel')),
    path('auth/', include('auth_user.urls', namespace='auth_user')),
    path('profile/', include('profile_user.urls', namespace='profile_user')),
    path('news/', include('news.urls', namespace='news')),
    path('about/', include('about.urls', namespace='about')),
    path('faq/', include('faq.urls', namespace='faq')),
    path('employee/', include('employee.urls', namespace='employee')),
    path('vacancy/', include('vacancy.urls', namespace='vacancy')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('review/', include('review.urls', namespace='review')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4th semester university/Lab4/mysite/profile_user/urls.py
from . import views
from django.urls import path

app_name = 'profile_user'

urlpatterns = [
    path('', views.get_book, name='profile'),
]

4th semester university/Lab4/mysite/hotel/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# https://django.fun/ru/docs/django/4.1/topics/db/models/
# https://django.fun/ru/docs/django/4.1/ref/models/fields/#model-field-types
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Room(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    capacity = models.IntegerField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    photo = models.ImageField(upload_to='static/rooms/', blank=True)

    def __str__(self):
        return f"Room {self.id} ({self.category})"


class Client(AbstractUser):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    patronymic = models.CharField(max_length=100)
    birth_date = models.DateField()
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.patronymic}"


class Booking(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    has_child = models.BooleanField(default=False)

    STATUS_CHOICES = [
        ('paid', 'Paid'),
        ('cart', 'Cart'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='cart')

    def __str__(self):
        return f"Booking {self.id} - {self.client} ({self.room})"

    def calculate_total_cost(self):
        duration = self.check_out_date - self.check_in_date
        return duration.days * self.room.price

4th semester university/Lab4/mysite/hotel/views.py
from datetime import datetime

from .models import Room, Category, Booking
from coupon.models import Coupon
from django.shortcuts import get_object_or_404
from django.db.models import Count
from django.utils import timezone
import calendar
import requests
import matplotlib.pyplot as plt
import io
import base64
from django.shortcuts import render, redirect
from django.conf import settings
import os


def timezone_context(request):
    quote = ''
    joke = ''
    if request.user.is_authenticated:
        url = 'http://api.forismatic.com/api/1.0/'
        params = {
            'method': 'getQuote',
            'format': 'json',
            'lang': 'en'
        }
        response = requests.get(url, params=params)

        url = "https://icanhazdadjoke.com/"
        headers = {"Accept": "application/json"}
        response_joke = requests.get(url, headers=headers)

        try:
            if response.status_code == 200 or response_joke.status_code == 200:
                data = response.json()
                quote = (data['quoteText'])
                joke = response_joke.json()['joke']
            else:
                quote = ('Ошибка при выполнении запроса:', response.status_code)
                joke = ('Ошибка при выполнении запроса:', response.status_code)
        except:
            quote = 'No internet connection'
            joke = 'No internet connection'

    user_timezone = timezone.get_current_timezone()
    current_date = timezone.now()
    c = calendar.HTMLCalendar(calendar.MONDAY).formatmonth(datetime.now().year, datetime.now().month)
    context = {
        'user_timezone': user_timezone,
        'current_date': current_date,
        'calendar': c,
        'quote': quote,
        'joke': joke,
    }
    return context


def room_list(request, category_id):
    def get_html():
        if category_id == 0:
            rooms = Room.objects.all()
        else:
            rooms = Room.objects.filter(category_id=category_id)

        categories = Category.objects.all()
        return render(request, 'hotel/hotel_list.html', {'rooms': rooms,
                                                         'categories': categories,
                                                         'choose_category': category_id,
                                                         'timezone_context': timezone_context(request)})

    if request.method == 'POST' and 'delete_room' in request.POST:
        room = get_object_or_404(Room, id=request.POST['room_id'])
        room.delete()
        return get_html()

    return get_html()


def sort_rooms_by_price(request, category_id):
    if category_id == 0:
        rooms = Room.objects.order_by('price')
    else:
        rooms = Room.objects.filter(category_id=category_id).order_by('price')

    categories = Category.objects.all()
    return render(request, 'hotel/hotel_list.html', {'rooms': rooms,
                                                     'is_sort_by_price': True,
                                                     'categories': categories,
                                                     'choose_category': category_id,
                                                     'timezone_context': timezone_context(request)})


def room_detail(request, room_id):
    def check_date_periods(start1, end1, start2, end2):
        if start1 < end2 and start2 < end1:
            return True
        else:
            return False

    form = get_object_or_404(Room, id=room_id)
    categories = Category.objects.all()
    coupon = ''
    count = ''

    if request.method == 'POST' and 'book_room' in request.POST:
        check_in_date = datetime.strptime(request.POST['check_in_date'], '%Y-%m-%d').date()
        check_out_date = datetime.strptime(request.POST['check_out_date'], '%Y-%m-%d').date()
        has_child = request.POST.get('my_checkbox', False)
        if check_in_date >= check_out_date:
            error_message = "Check in date <= Check out date!"
            return render(request, 'hotel/room_detail.html', {'error_message': error_message})

        periods = []

        all_booking = Booking.objects.filter(room_id=room_id)
        for i in all_booking:
            if check_date_periods(check_in_date, check_out_date, i.check_in_date, i.check_out_date):
                periods.append(str(i.check_in_date) + ' --> ' + str(i.check_out_date))

        if len(periods):
            error_message = "Already booked these days: " + str(periods) + '!'
            return render(request, 'hotel/room_detail.html', {'error_message': error_message})

        booking = Booking(
            room=form,
            client=request.user,
            check_in_date=check_in_date,
            check_out_date=check_out_date,
            has_child=True if has_child == "on" else False
        )
        booking.save()
        return redirect("profile_user:profile")

    if request.method == 'POST' and 'edit_room' in request.POST:
        price = request.POST['price']
        capacity = request.POST['capacity']
        select = request.POST['select']
        photo = request.FILES['photo']

        file_path = os.path.join(settings.MEDIA_ROOT, 'rooms')
        with open(file_path, 'wb') as destination:
            for chunk in photo.chunks():
                destination.write(chunk)

        category = get_object_or_404(Category, id=select)
        form.category = category
        form.capacity = capacity
        form.price = price
        form.photo = photo

        form.save()
        form = get_object_or_404(Room, id=room_id)

    if request.method == 'POST' and 'coupon' in request.POST:
        text = request.POST['text']
        coupons = Coupon.objects.filter(code=text, is_active=True)
        if coupons.exists():
            coupon = coupons.first()
            try:
                count = "{:.2f}".format(float(coupon.description[:-1]) / 100)
            except:
                coupon = ''

    return render(request, 'hotel/room_detail.html',
                  {'form': form, 'categories': categories, 'coupon': coupon, 'count': count})


def create_room(request):
    if not request.user.is_authenticated:
        return redirect("hotel:hotel_list", 0)

    categories = Category.objects.all()
    if request.method == 'POST' and 'create_room' in request.POST:
        price = request.POST['price']
        capacity = request.POST['capacity']
        select = request.POST['select']
        photo = request.FILES['photo']

        file_path = os.path.join(settings.MEDIA_ROOT, 'rooms')
        with open(file_path, 'wb') as destination:
            for chunk in photo.chunks():
                destination.write(chunk)

        category = get_object_or_404(Category, id=select)

        new_room = Room()
        new_room.category = category
        new_room.photo = photo
        new_room.capacity = capacity
        new_room.price = price
        new_room.save()
        return redirect("hotel:hotel_list", 0)

    return render(request, 'hotel/room_create.html', {'categories': categories})


def analyse(request):
    if not request.user.is_authenticated:
        return redirect("hotel:hotel_list", 0)

    try:
        bookings = Booking.objects.all()
        list_total_cost = [booking.calculate_total_cost() for booking in bookings]
        sum_cost = sum(list_total_cost)

        average_bill = sum_cost / len(list_total_cost)

        popular_rooms = Booking.objects.values('room').annotate(total_bookings=Count('room')). \
            order_by('-total_bookings').first()
        total_bookings = popular_rooms['total_bookings']
        room = Room.objects.get(id=popular_rooms['room'])

        plt.plot(list_total_cost)
        buf = io.BytesIO()
        plt.savefig(buf, format='png')
        buf.seek(0)
        plot_data = base64.b64encode(buf.read()).decode('ascii')

        return render(request, 'hotel/hotel_analyse.html', {'bookings': bookings,
                                                            'total_earnings': sum_cost,
                                                            'average_bill': average_bill,
                                                            'total_bookings': total_bookings,
                                                            'most_popular_room': room,
                                                            'plot_data': plot_data})
    except:
        return render(request, 'hotel/hotel_analyse.html', {'bookings': None,
                                                            'total_earnings': None,
                                                            'average_bill': None,
                                                            'total_bookings': None,
                                                            'most_popular_room': None,
                                                            'plot_data': None})

4th semester university/Lab4/mysite/hotel/templates/hotel/base_hotel.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Klimkovich Nikolay">
    <title>Hotel</title>
    <link rel="icon" href="/static/logo/logo.png" type="image/x-icon">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="/static/css/footer-header.css">
    <link rel="stylesheet" href="/static/css/other.css">
    {% block head %} {% endblock %}
</head>
<body>
<div class="loader"></div>
<script src="/static/js/base.js"></script>

<div class="box-items-1">
    <div class="whiteImage"></div>
    <div class="blackYellowImage"></div>
</div>
<div class="wrapper">
    <header class="menu">
        <label class="logo" onclick="window.location.href='{%url 'main:home' %}';">HOTEL</label>
        <div class="menu-items">
            <label class="my-button" onclick="window.location.href='{%url 'hotel:hotel_list' 0 %}';">ROOMS</label>
            <label class="my-button" onclick="window.location.href='{%url 'review:home' %}';">REVIEW</label>
            <select class="select-1" onchange="window.location.href=this.value;">
                <option value="" selected disabled>MENU</option>
                <option value="{%url 'news:home' %}">NEWS</option>
                <option value="{%url 'faq:home' %}">FAQ</option>
                <option value="{%url 'employee:home' %}">CONTACTS</option>
                <option value="{%url 'coupon:home' %}">COUPONS</option>
                <option value="{%url 'about:home' %}">ABOUT</option>
            </select>

            {% if user.is_authenticated %}

            <div>
                <label class="my-button">{{user.username}}</label>
                <label class="my-button" onclick="location.href='{%url 'auth_user:logout' %}'">Sign Out</label>
            </div>
            {% else %}
            <div>
                <label class="my-button" onclick="location.href='{%url 'auth_user:register' %}'">Up</label>
                <label class="my-button" style="cursor: default">/</label>
                <label class="my-button" onclick="location.href='{%url 'auth_user:login' %}'">In</label>
            </div>
            {% endif %}
        </div>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <a class="my-button" href="/static/policy/policy.pdf" download="Privacy_Policies.pdf">PRIVACY POLICIES</a>
        <label class="my-button" onclick="window.location.href='{%url 'vacancy:home' %}';">VACANCY</label>
    </footer>
</div>
<div class="box-items-2">
    <div class="yellowImage"></div>
    <div class="greenImage"></div>
</div>


</body>
</html>

4th semester university/Lab4/mysite/hotel/templates/hotel/hotel_analyse.html
{% extends 'hotel/base_hotel.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/coupon.css">
{% endblock %}

{% block content %}
<Label class="room-text">Total earnings: {{total_earnings}}</Label><br>
<Label class="room-text">Average bill: {{average_bill}}</Label><br><br>
<Label class="room-text">The most popular room: {{most_popular_room}}</Label><br>
<Label class="room-text">It has a total of {{total_bookings}} bookings</Label><br>

<img src="data:image/png;base64,{{ plot_data }}">

<ul class="room-list">
    {% for booking in bookings %}
    <li class="room-item">
        <div class="room-text">
            <label>Name: {{ booking.client }}</label><br>
            <label>Phone: {{ booking.client.phone_number }}</label><br>
            <label>Has child: {{ booking.has_child }}</label><br>
            <label>Check-In: {{ booking.check_in_date }}</label><br>
            <label>Check-Out: {{ booking.check_out_date }}</label><br>
            <label>Status: {{ booking.status }}</label><br>
            <label>Total cost: {{ booking.calculate_total_cost }}</label>
        </div>
    </li>
    {% empty %}
    <li>No booking</li>
    {% endfor %}
</ul>

<table border="2" >
    <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Has child</th>
        <th>Check-In</th>
        <th>Check-Out</th>
        <th>Status</th>
        <th>Total cost</th>
    </tr>
    {% for booking in bookings %}
    <tr>
        <td>{{ booking.client }}</td>
        <td> {{ booking.client.phone_number }}</td>
        <td> {{ booking.has_child }}</td>
        <td> {{ booking.check_in_date }}</td>
        <td> {{ booking.check_out_date }}</td>
        <td>{{ booking.status }}</td>
        <br>
        <td> {{ booking.calculate_total_cost }}</td>
    </tr>
    {% empty %}
    <li>No booking</li>
    {% endfor %}
</table>
{% endblock %}

4th semester university/Lab4/mysite/hotel/templates/hotel/hotel_list.html
{% extends 'hotel/base_hotel.html' %}

{% block head %}
<link rel="stylesheet" href="/static/css/rooms.css">
{% endblock %}

{% block content %}
<div class="all-item">
    {% if user.is_authenticated and not user.is_superuser %}
    <div class="but1">
        <label class="button-1" style="float: right;"
               onclick="window.location.href = '{% url 'profile_user:profile' %}'">Profile
        </label>
    </div>
    {% endif %}

    {% if user.is_superuser %}
    <div class="but2">
        <label class="button-1" style="float: right;"
               onclick="window.location.href = '{% url 'hotel:hotel_analyse' %}'">Analyse
        </label>
        <label class="button-1" style="float: right;"
               onclick="window.location.href = '{% url 'hotel:room_create' %}'">Add
        </label>
    </div>
    {%endif%}

    <div class="but3">
        {% if is_sort_by_price %}
        <label class="button-1" style="float: right;"
               onclick="window.location.href = '{% url 'hotel:hotel_list' choose_category%}'">
            Sort by Price
        </label>
        {% else %}
        <label class="button-1" style="float: right;"
               onclick="window.location.href = '{% url 'hotel:hotel_list_sort_by_price' choose_category%}'">
            Sort by Price
        </label>
        {% endif %}

        <select class="select-1" style="float: right;" id="categorySelector" onchange="redirectToSelectedCategory()"
                onselect=choose_category>
            <option value="{% url 'hotel:hotel_list' 0 %}">All</option>
            {% for category in categories %}
            <option value="{% url 'hotel:hotel_list' category.id %}"
                    {% if category.id == choose_category %}
                    selected
                    {% endif %}>
                {{ category.name }}
            </option>
            {% endfor %}
        </select>
        <script>
            function redirectToSelectedCategory() {
                var selectedOption = document.getElementById("categorySelector").value;
                window.location.href = selectedOption;
            }
        </script>

    </div>
    {% if user.is_authenticated or user.is_superuser %}
    <div class="api">
        <label>Quote: {{timezone_context.quote}}</label><br>
        <label>Joke: {{timezone_context.joke}}</label>
    </div>
    {%endif%}
    <ul>
        {% for m in rooms %}
        <li class="card-wrapper" onclick="window.location.href='{% url 'hotel:room_id' m.id %}'">
            {% load static %}
            <div class="card">
                <div style="height:250px;"></div>
                <div class="name-room">{{ m }}</div>
                <div>Capacity: {{ m.capacity }}</div>
                <div>Price: {{ m.price }}</div>
                {% if user.is_superuser%}
                <form method="POST">
                    {% csrf_token %}
                    <input class="input-1" type="hidden" name="room_id" value="{{ m.id }}">
                    <button id="delete" name="button1" class="button-1 button-card">
                        Delete
                    </button>
                </form>
                {%endif%}
            </div>
            <img class="image-card" src="/{{ m.photo }}" alt="image">
        </li>
        {% empty %}
        <li>No rooms</li>
        {% endfor %}
    </ul>

    <header class="but5">
        <div><br>
            {{ timezone_context.calendar|safe }}<br>
            <label>User Timezone: {{ timezone_context.user_timezone }} |</label>
            <label>Current Date: {{ timezone_context.current_date|date:"d/m/Y" }} </label>
        </div>
    </header>
</div>
<script src="/static/js/rooms.js"></script>
{% endblock %}

4th semester university/Lab4/mysite/hotel/templates/hotel/room_create.html
{% extends 'hotel/base_hotel.html' %}

{% block content %}
{% if user.is_superuser %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="text-align: center;" class="room-text">
        <label >Price:</label>
        <input class="input-1"  type="number" min="0" step="any" name="price" required><br>

        <label >Capacity:</label>
        <input class="input-1"  type="number" min="0" name="capacity" required><br>

        <label>Photo:</label>
        <input class="input-1"  type="file" name="photo" required><br>

        <label >Category:</label>
        <select class="select-1" name="select">
            {% for category in categories %}
            <option value="{{ category.id }}"> {{ category.name }}</option>
            {% endfor %}
        </select><br><br>

        <button class="button-1" name="create_room">Create</button>
    </div>
</form>
{%endif%}

{% endblock %}

4th semester university/Lab4/mysite/hotel/templates/hotel/room_detail.html
{% extends 'hotel/base_hotel.html' %}

{% block head %}
<link rel="stylesheet" href="/static/css/news.css">
{% endblock %}

{% block content %}
{% load static %}
<div style="text-align: center;">
    <img class="myimg" src="/{{ form.photo }}" alt="My image">
    <div>{{ form }}</div>
    <div>Capacity: {{ form.capacity }}</div>
    <label>Price: </label> <label id="price">{{ form.price }}</label>
    <br><br>

    {% if user.is_authenticated and not user.is_superuser%}

    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <div style="text-align: center;">
            <label>Coupon:</label>
            <div hidden id="count">{{ count }}</div>
            <input class="input-1" type="text" id="coupon" name="text" value="{{ coupon }}">
            <button class="button-1" name="coupon">Apply</button>
        </div>
    </form>
    <br><br>

    <form method="POST">
        {% csrf_token %}
        <div style="text-align: center;">
            <label>Check-in date</label>
            <input class="input-1" type="date" name="check_in_date" required><br>

            <label>Disabled</label>
            <input class="input-1" type="date" name="check_in_date" disabled><br>

            <label>Check-Out date:</label>
            <input class="input-1" type="date" name="check_out_date" required><br>

            <label>Has_child (+5%):</label>
            <input class="input-1" type="checkbox" name="has_child" id="check"><br><br>

            <label>Total price: </label><label id="total"></label><br>
            <button class="button-1" name="book_room">Book a room</button>
        </div>
    </form>
    <br><br>
</div>
{%endif%}

{% if user.is_superuser %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="text-align: center;">
        <label>Price:</label>
        <input class="input-1" type="number" min="0" step="any" name="price" required><br>

        <label>Capacity:</label>
        <input class="input-1" type="number" min="0" max="10" name="capacity" required><br>

        <label>Photo:</label>
        <input class="input-1" type="file" name="photo" required><br>

        <label>Category:</label>
        <select class="register-button" name="select">
            {% for category in categories %}
            <option value="{{ category.id }}"> {{ category.name }}</option>
            {% endfor %}
        </select><br>

        <button class="button-1" name="edit_room">Edit</button>
    </div>
</form>
{%endif%}

<script src="/static/js/room_coupon.js"></script>
{% endblock %}