4th semester university/Lab4/mysite/faq/urls.py
from . import views
from django.urls import path

app_name = 'faq'

urlpatterns = [
    path('', views.faq_list, name='home'),
]

4th semester university/Lab4/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('hotel/', include('hotel.urls', namespace='hotel')),
    path('auth/', include('auth_user.urls', namespace='auth_user')),
    path('profile/', include('profile_user.urls', namespace='profile_user')),
    path('news/', include('news.urls', namespace='news')),
    path('about/', include('about.urls', namespace='about')),
    path('faq/', include('faq.urls', namespace='faq')),
    path('employee/', include('employee.urls', namespace='employee')),
    path('vacancy/', include('vacancy.urls', namespace='vacancy')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('review/', include('review.urls', namespace='review')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4th semester university/Lab4/mysite/news/urls.py
from . import views
from django.urls import path

app_name = 'news'

urlpatterns = [
    path('', views.news_list, name='home'),
    path('<int:news_id>/', views.current_news, name='current_news'),
]

4th semester university/Lab4/mysite/news/models.py
from django.db import models


class News(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    publication_date = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to='static/news/')

    def __str__(self):
        return self.title

4th semester university/Lab4/mysite/news/views.py
from django.shortcuts import render, get_object_or_404
from .models import News


def news_list(request):
    news_list = News.objects.order_by('-publication_date')
    context = {
        'news_list': news_list,
    }
    return render(request, 'news.html', context)

def current_news(request, news_id):
    news = get_object_or_404(News, pk=news_id)
    context = {
        'news': news,
    }
    return render(request, 'current_news.html', context)

4th semester university/Lab4/mysite/news/templates/current_news.html
{% extends 'hotel/base_hotel.html' %}
{% block head %}
<link rel="stylesheet" href="/static/css/news.css">
{% endblock %}

{% block content %}

<h1 style="margin:40px;">{{ news.title }}</h1>
<img class="myimg" src="{{ news.image.url }}" alt="{{ news.title }}" width="400">
<p>{{ news.content }}</p>

{% endblock %}

4th semester university/Lab4/mysite/news/templates/news.html
{% extends 'hotel/base_hotel.html' %}

{% block head %}
<meta name="description" content="Последние новости и статьи">
<meta name="keywords" content="новости, статьи, информация">
<link rel="stylesheet" href="/static/css/news.css">
{% endblock %}

{% block content %}

<ul>
    {% for news in news_list %}
    <li itemscope itemtype="http://schema.org/NewsArticle">
        <h3 itemprop="headline">{{ news.title }}</h3>
        <img itemprop="image" src="{{ news.image.url }}" alt="{{ news.title }}" width="100">
        <p itemprop="description">{{ news.content }}</p>
        <a itemprop="url" href="{% url 'news:current_news' news.id %}">Читать далее</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}